### ISSUE TITLE
Update the repair procedure

### ISSUE THREAD

**Issue by karol-kokoszka** [scylladb/scylla-manager#3423]
This is the epic that groups all tasks related to `repair` procedure fixes and updates.
https://manager.docs.scylladb.com/stable/repair/

The requirements for `repair` procedure are as follow:
- Repair keyspace by keyspace (in the context of manager repair task) ordered by their total size
- Repair table by table (in the context of repairing the keyspace)
- Repair MV and si after the base table (only when CQL credentials are available)
- Execute max `--parallel` repair job per host
- Start repair job on the replica node with smallest shard count
- Repair system tables before user tables

Full design doc is here https://docs.google.com/document/d/1mBaufbomXU6hDO_25KkhC7CO65AbFgKpHVpB5Mei8xA/edit
(visible for people from ScyllaDB org only).

The idea is to update/align current implementation of repair to the given requirements.

```[tasklist]
### Tasks
- [ ] https://github.com/scylladb/scylla-manager/issues/3424
- [ ] https://github.com/scylladb/scylla-manager/issues/3425
- [ ] https://github.com/scylladb/scylla-manager/issues/3362
- [ ] https://github.com/scylladb/scylla-manager/issues/3367
- [ ] https://github.com/scylladb/scylla-manager/issues/3426
- [ ] https://github.com/scylladb/scylla-manager/issues/3463
- [ ] https://github.com/scylladb/scylla-manager/issues/3515
```

**Comment by karol-kokoszka** [comment]
Epic should be started with this issue https://github.com/scylladb/scylla-manager/issues/3424
It will remove quite much of not needed (and complicated) code.
