### ISSUE TITLE
Improve restore performance

### ISSUE THREAD

**Issue by Michal-Leszczynski** [scylladb/scylla-manager#3706]
```[tasklist]
### Possible restore performance improvements
- [ ] https://github.com/scylladb/scylla-manager/issues/3948
- [ ] https://github.com/scylladb/scylla-manager/issues/3947
- [ ] https://github.com/scylladb/scylla-manager/issues/3946
- [ ] https://github.com/scylladb/scylla-manager/issues/3660
- [ ] https://github.com/scylladb/scylla-manager/issues/3951
- [ ] https://github.com/scylladb/scylla-manager/issues/3705
- [ ] https://github.com/scylladb/scylla-manager/issues/3809
- [ ] https://github.com/scylladb/scylla-manager/issues/3953
- [ ] https://github.com/scylladb/scylladb/issues/19989
- [ ] https://github.com/scylladb/scylla-manager/issues/3979
- [ ] https://github.com/scylladb/scylla-manager/issues/3981
- [ ] https://github.com/scylladb/scylla-manager/issues/3982
- [ ] https://github.com/scylladb/scylla-manager/issues/3983
```

**Comment by mykaul** [comment]
I'd add https://github.com/scylladb/scylla-manager/issues/3660 to this. I think it may add value - worth running a quick check.

**Comment by Michal-Leszczynski** [comment]
@mykaul @tzach I refreshed the task list of this issue and will use it as the epic for restore performance improvement.

**Comment by mykaul** [comment]
I don't see the item about the different sstable sizes sent in a batch to a node - improve it by sorting by size  ( https://github.com/scylladb/scylla-manager/pull/3970 ?)

**Comment by Michal-Leszczynski** [comment]
This epic was supposed to track restore improvements targeting SM 3.4 release, which is already out.
The only not-implemented/not-evaluated issue is https://github.com/scylladb/scylla-manager/issues/3660, which focuses more about backup performance/speed.

I'm leaving the compression issue open, so that we can implement it in the future, but I'm closing this epic, because it fulfilled its goal.
